RENOMEAR_COLUNAS = {
    "title": "Nome",
    "address": "Endereço",
    "phone": "Telefone",
    "website": "Website",
    "agendar_on_line": "Agendamento Online",
    "rating": "Avaliação",
    "reviews": "Nº de Avaliações",
    "gps_coordinates": "Coordenadas GPS",
    "open_state": "Horário",
    "type": "Categoria",
    "types": "Categorias",
    "type_id": "Categoria (ID)",
    "type_ids": "Categorias (IDs)",
    "place_id": "Place ID",
    "data_id": "ID Interno",
    "data_cid": "CID",
    "provider_id": "Provider ID",
    "reviews_link": "Link Avaliações",
    "photos_link": "Link Fotos",
    "thumbnail": "Miniatura",
    "serpapi_thumbnail": "Miniatura SerpAPI",
    "unclaimed_listing": "Listagem Não Reivindicada",
    "extensions": "Atributos Extras",
    "unsupported_extensions": "Atributos Não Suportados",
    "service_options": "Opções de Serviço",
}